#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
import sys, select, termios, tty

BURGER_MAX_LIN_VEL = 2.5
BURGER_MAX_ANG_VEL = 7

WAFFLE_MAX_LIN_VEL = 1
WAFFLE_MAX_ANG_VEL = 5

LIN_VEL_STEP_SIZE = 0.1
ANG_VEL_STEP_SIZE = 0.5

msg = """

---------------------------
Moving around:
   q    w    r
   a    s    d
        

space key, s : force stop

CTRL-C to quit
"""

e = """
Communications Failed
"""

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

def vels(target_linear_vel, target_angular_vel):
    return "currently:\tlinear vel %s\t angular vel %s " % (target_linear_vel,target_angular_vel)

def makeSimpleProfile(output, input, slop):
    if input > output:
        output = min( input, output + slop )
    elif input < output:
        output = max( input, output - slop )
    else:
        output = input

    return output

def constrain(input, low, high):
    if input < low:
      input = low
    elif input > high:
      input = high
    else:
      input = input

    return input

def checkLinearLimitVelocity(vel):
    if turtlebot3_model == "burger":
      vel = constrain(vel, -BURGER_MAX_LIN_VEL, BURGER_MAX_LIN_VEL)
    elif turtlebot3_model == "waffle" or turtlebot3_model == "waffle_pi":
      vel = constrain(vel, -WAFFLE_MAX_LIN_VEL, WAFFLE_MAX_LIN_VEL)
    else:
      vel = constrain(vel, -BURGER_MAX_LIN_VEL, BURGER_MAX_LIN_VEL)

    return vel

def checkAngularLimitVelocity(vel):
    if turtlebot3_model == "burger":
      vel = constrain(vel, -BURGER_MAX_ANG_VEL, BURGER_MAX_ANG_VEL)
    elif turtlebot3_model == "waffle" or turtlebot3_model == "waffle_pi":
      vel = constrain(vel, -WAFFLE_MAX_ANG_VEL, WAFFLE_MAX_ANG_VEL)
    else:
      vel = constrain(vel, -BURGER_MAX_ANG_VEL, BURGER_MAX_ANG_VEL)

    return vel

if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin)

    rospy.init_node('turtlebot3_teleop')
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

    turtlebot3_model = rospy.get_param("model", "burger")

    status = 0
    target_linear_vel   = 0.0
    target_linear_y_vel   = 0.0
    target_angular_vel  = 0.0
    control_linear_vel  = 0.0
    control_linear_y_vel  = 0.0
    control_angular_vel = 0.0

    try:
        print msg
        while(1):
            key = getKey()
            if key == 'w' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel + WAFFLE_MAX_LIN_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 's' :
                target_linear_vel = checkLinearLimitVelocity(target_linear_vel - WAFFLE_MAX_LIN_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'q' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel + WAFFLE_MAX_ANG_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'e' :
                target_angular_vel = checkAngularLimitVelocity(target_angular_vel - WAFFLE_MAX_ANG_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'a' :
                target_linear_y_vel = checkLinearLimitVelocity(target_linear_y_vel+WAFFLE_MAX_LIN_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == 'd' :
                target_linear_y_vel = checkLinearLimitVelocity(target_linear_y_vel-WAFFLE_MAX_LIN_VEL)
                status = status + 1
                print vels(target_linear_vel,target_angular_vel)
            elif key == '\x03':
                break
                
            else:
                target_linear_vel   = 0.0
                control_linear_vel  = 0.0
                target_linear_y_vel = 0.0
                target_angular_vel  = 0.0
                control_angular_vel = 0.0

            if status == 20 :
                print msg
                status = 0

            twist = Twist()

            control_linear_vel = makeSimpleProfile(control_linear_vel, target_linear_vel, (LIN_VEL_STEP_SIZE/2.0))
            twist.linear.x = control_linear_vel; twist.linear.y = target_linear_y_vel; twist.linear.z = 0.0

            control_angular_vel = makeSimpleProfile(control_angular_vel, target_angular_vel, (ANG_VEL_STEP_SIZE/2.0))
            twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = control_angular_vel

            pub.publish(twist)

    except:
        print e

    finally:
        twist = Twist()
        twist.linear.x = 0.0; twist.linear.y = 0.0; twist.linear.z = 0.0
        twist.angular.x = 0.0; twist.angular.y = 0.0; twist.angular.z = 0.0
        pub.publish(twist)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
